CREATE TABLE STAFFAPP.APP_USER
(
  ID          NUMBER(19)                        NOT NULL,
  EMAIL       VARCHAR2(255 CHAR),
  ENABLED     NUMBER(1),
  FIRST_NAME  VARCHAR2(255 CHAR),
  LAST_NAME   VARCHAR2(255 CHAR),
  LOCKED      NUMBER(1),
  PASSWORD    VARCHAR2(255 CHAR),
  USER_ROLE   VARCHAR2(255 CHAR)
)
TABLESPACE STAFFAPP_DAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


ALTER TABLE STAFFAPP.APP_USER ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE STAFFAPP_DAT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);




