
CREATE TABLE STAFFAPP.APP_LOCATION
(
  ID               NUMBER(19)                   NOT NULL,
  AVAILABLE        NUMBER(1),
  CREATED_AT       TIMESTAMP(6)                 NOT NULL,
  DESCRIPTION      VARCHAR2(255 CHAR),
  LOCATION_NUMBER  NUMBER(19)                   NOT NULL,
  MODIFIED_AT      TIMESTAMP(6),
  APP_EMPLOYEE_ID  NUMBER(19)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX STAFFAPP.UK_BQ3DXF1WRP1GFU7UR293YPU2B ON STAFFAPP.APP_LOCATION
(LOCATION_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE STAFFAPP.APP_LOCATION ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE
,  CONSTRAINT UK_BQ3DXF1WRP1GFU7UR293YPU2B
  UNIQUE (LOCATION_NUMBER)
  USING INDEX STAFFAPP.UK_BQ3DXF1WRP1GFU7UR293YPU2B
  ENABLE VALIDATE);


--  There is no statement for index STAFFAPP.SYS_C008046.
--  The object is created when the parent object is created.
