CREATE TABLE STAFFAPP.APP_ITEM_HIST
(
  ID               NUMBER(19)                   NOT NULL,
  ITEM_ID          NUMBER(19),
  BARCODE          VARCHAR2(255 CHAR)           NOT NULL,
  CREATED_AT       TIMESTAMP(6)                 NOT NULL,
  DESCRIPTION      VARCHAR2(255 CHAR)           NOT NULL,
  ENABLED          NUMBER(1),
  IMAGE            BLOB,
  ITEM_NAME        VARCHAR2(255 CHAR)           NOT NULL,
  ITEM_TYPE        VARCHAR2(255 CHAR)           NOT NULL,
  MANUFACTURED_AT  TIMESTAMP(6)                 NOT NULL,
  MODIFIED_AT      TIMESTAMP(6),
  APP_EMPLOYEE_ID  NUMBER(19),
  APP_LOCATION_ID  NUMBER(19)
)
LOB (IMAGE) STORE AS SECUREFILE (
  TABLESPACE  STAFFAPP_DAT
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING)
TABLESPACE STAFFAPP_DAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;


CREATE UNIQUE INDEX STAFFAPP.UK_LG2DREPB1F36J8TEBNOGYOU84 ON STAFFAPP.APP_ITEM_HIST
(BARCODE)
LOGGING
TABLESPACE STAFFAPP_DAT
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE STAFFAPP.APP_ITEM_HIST ADD (
  PRIMARY KEY
  (ID)
  USING INDEX
    TABLESPACE STAFFAPP_DAT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE
,  CONSTRAINT UK_LG2DREPB1F36J8TEBNOGYOU84
  UNIQUE (BARCODE)
  USING INDEX STAFFAPP.UK_LG2DREPB1F36J8TEBNOGYOU84
  ENABLE VALIDATE);


--  There is no statement for index STAFFAPP.SYS_C00199868.
--  The object is created when the parent object is created.

